### ISSUE TITLE
Need help for lambda issue

### ISSUE THREAD

**Issue by aaditya1903** [aws-samples/experimental-programmatic-access-ccft#10]
Hello, I am trying to obtain the CO2e data for another account in my organisation and store into an s3 bucket folder through a lambda function. However, running this lambda code results in a 403 client error, forbidden url. Is this issue to do with permissions? In which case, what permissions do I need to make sure my account has in order for this to work. Or is there something wrong with the code? Thank you for your help.

The lambda code:
`import boto3

import os

import ccft_access

import json

from datetime import datetime, date

from dateutil.relativedelta import relativedelta

from urllib.parse import urlencode

def lambda_handler(event, context):

    #account = event

    s3 = boto3.resource('s3')

    sts_client = boto3.client('sts')

    s3_bucket = os.environ['bucketName']

    role_name = os.environ['ccftRole']

    s3_obj_name = os.environ['fileName']

    request_id = context.aws_request_id

   

    # calculate three months past (when new carbon emissions data is available)

    three_months = date.today() + relativedelta(months=-3)

    # get the date with 1st day of the month

    year = three_months.year

    month = three_months.month

    first_date = datetime(year, month, 1)

   

    # If you want to extract carbon emissions data for a different time frame, you can change it manually here

    start_date=first_date.strftime("%Y-%m-%d")

    end_date=first_date.strftime("%Y-%m-%d")

 

    # Create a new session and get credentials from target role

    target_account_role_arn = "arn:aws:iam::[accountnumber]:role/[role]"

    target_account_role = sts_client.assume_role(

        RoleArn=target_account_role_arn,

        RoleSessionName="sustainability_reader_session"

    )

   

    new_access_key_id = target_account_role["Credentials"]["AccessKeyId"]

    new_secret_access_key = target_account_role["Credentials"]["SecretAccessKey"]

    new_session_token = target_account_role["Credentials"]["SessionToken"]

 

    new_session = boto3.Session(

        aws_access_key_id=new_access_key_id,

        aws_secret_access_key=new_secret_access_key,

        aws_session_token=new_session_token

    )

   

    credentials = new_session.get_credentials()

 

    try:

        emissions_data = ccft_access.extract_emissions_data(start_date, end_date, credentials)

 

        # check if new emissions data is available

        carbonEmissionEntries = emissions_data['emissions']['carbonEmissionEntries']

        if len(carbonEmissionEntries) == 0:

            isDataAvailable = False

            message = "No new data is available"

        else:

            isDataAvailable = True

            # save json to file in s3 bucket

            s3_obj_name = str(request_id)+"_"+str(start_date)+"carbon_emissions.json"

            # s3_obj_name = str(account)+"/"+str(request_id)+"_"+str(start_date)+"carbon_emissions.json"

            s3.Object(s3_bucket, s3_obj_name).put(Body=json.dumps(emissions_data))

            message = "Successfully saved data to S3 bucket for account"

       

        return {

            'message': message,

            'isDataAvailable': isDataAvailable

        }       

 

    except Exception as e:

        #If account is less than three months old, no carbon emissions data will be available

        message = str(e)

        if str(e) == "404 Client Error: Not Found for url: https://us-east-1.console.aws.amazon.com/billing/rest/api-proxy/carbonfootprint":

            message = "No carbon footprint report is available for account at this time. If no report is available, your account might be too new to show data. There is a delay of three months between the end of a month and when emissions data is available."

        return {

                'message': message,

                'isDataAvailable': False

            }`
            
          
The error:
"message": "An error occured: 403 Client Error: Forbidden for url: https://us-east-1.console.aws.amazon.com/billing/rest/api-proxy/carbonfoorprint", "isDataAvailable": false

**Comment by steffeng** [comment]
Hi @aaditya1903, see this [faq entry](https://github.com/aws-samples/experimental-programmatic-access-ccft?tab=readme-ov-file#q-what-permissions-are-needed-to-run-this) for the permissions required. If you want to run this script on a regular basis, you can also deploy the [multi-account stack](https://github.com/aws-samples/experimental-programmatic-access-ccft?tab=readme-ov-file#multi-account-extraction-faq) and [override the account id](https://github.com/aws-samples/experimental-programmatic-access-ccft?tab=readme-ov-file#q-how-can-i-specify-the-account-ids-to-retrieve-data-from) with this other account in your org (if you don't want to get the data for all accounts in your org).
