### ISSUE TITLE
Replace piecharts with different visualization

### ISSUE THREAD

**Issue by ArlindNocaj** [aws-samples/experimental-programmatic-access-ccft#14]
Please note that piecharts are not that useful, and should be replaced 

https://theconversation.com/heres-why-you-should-almost-never-use-a-pie-chart-for-your-data-214576#:~:text=The%20pie%20chart's%20circularity%20means%20the%20areas%20lack%20a%20common%20reference%20point.&text=Pie%20charts%20also%20do%20badly,of%20categories%20in%20one%20pie.

**Comment by steffeng** [comment]
@ArlindNocaj, thanks for the feedback. This repository does not create pie charts but just includes screenshots of the AWS Customer Carbon Footprint Tool in the AWS management console. However, we passed your the feedback to the service team. If you have further feedback to the CCFT, you can also use the feedback link in the AWS management console directly in the lower left of every page.

**Comment by ArlindNocaj** [comment]
Ah ok, thanks for the hint. Lets close this one then.

Steffen Grunwald ***@***.***> schrieb am Di. 6. Aug. 2024 um
16:41:
