### ISSUE TITLE
The endpoint does not return the region and service type detail

### ISSUE THREAD

**Issue by mehdi-jafari** [aws-samples/experimental-programmatic-access-ccft#17]
When we invoke the sustainability endpoint:

**URL**: https://us-east-1.console.aws.amazon.com/billing/rest/api-proxy/carbonfootprint with 
**BODY** :
cft_request = {
        "headers": {
            "Content-Type": "application/json"
        },
        "path": "/get-carbon-footprint-summary",
        "method": "GET",
        "region": "us-east-1",
        "params": {
            "startDate": "2024-01-01",
            "endDate": "2024-07-01"
        }
    }
    cft_headers = {
        "x-awsbc-xsrf-token": xsrf_token
    }
    
    We only receive the following columns in the result:
    
carbonInefficiency | mbmCarbon | startDate
-- | -- | --
0.047 | 0.021 | 2022-01-01
1.779 | 0.626 | 2023-01-01
0.982 | 0.339 | 2024-01-01
0.968 | 0.129 | 2025-01-01
0.765 | 0.107 | 2026-01-01
0.648 | 0.098 | 2027-01-01

How can we get the service type for all the regions in the result?

**Comment by steffeng** [comment]
Greetings, @mehdi-jafari! The script can only present the data available in the CCFT console. You can find [the mapping of json fields here](https://github.com/aws-samples/experimental-programmatic-access-ccft?tab=readme-ov-file#q-how-does-the-data-relate-to-what-i-see-in-the-aws-customer-carbon-footprint-tool). The `carbonEmissionsForecast` does not have product code resolution. The past entries in `carbonEmissionEntries` have.

If you see more information in the console than in the json, please past the full json response from the script here. Feel free to redact your account id of course.

**Comment by mehdi-jafari** [comment]
Thank you for your prompt answer.
how can we ensure that we have the data available per region and service type such as EC2, S3 and ....
do I need to open a ticket with AWS to get that breakdown?

**Comment by steffeng** [comment]
@mehdi-jafari, the `carbonEmissionEntries` in the json has the same granularity as the [CCFT console](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/ccft-overview.html): _EC2_, _S3_, and _Other_. For any further feedback or asks, a support ticket is a good next step. If there's something not working with the experimental programmatic access from this repository, please reach out here.
